sudo: false
env:
#  - CARGS="--enable-linux --disable-multilib --with-arch=rv32imac --with-abi=ilp32"
#  - CARGS="--enable-linux --disable-multilib --with-arch=rv32imafdc --with-abi=ilp32"
#  - CARGS="--enable-linux --disable-multilib --with-arch=rv32imafdc --with-abi=ilp32d"
#  - CARGS="--enable-linux --disable-multilib --with-arch=rv64imac --with-abi=lp64"
#  - CARGS="--enable-linux --disable-multilib --with-arch=rv64imafdc --with-abi=lp64"
#  - CARGS="--enable-linux --disable-multilib --with-arch=rv64imafdc --with-abi=lp64d"
   - CARGS="--disable-linux --disable-multilib --with-arch=rv32i --with-abi=ilp32"
   - CARGS="--disable-linux --disable-multilib --with-arch=rv32im --with-abi=ilp32"
   - CARGS="--disable-linux --disable-multilib --with-arch=rv32iac --with-abi=ilp32"
   - CARGS="--disable-linux --disable-multilib --with-arch=rv32imac --with-abi=ilp32"
   - CARGS="--disable-linux --disable-multilib --with-arch=rv32imafc --with-abi=ilp32f"
   - CARGS="--disable-linux --disable-multilib --with-arch=rv64imac --with-abi=lp64"
   - CARGS="--disable-linux --disable-multilib --with-arch=rv64imafdc --with-abi=lp64d"


matrix:
  include:
  - os: osx
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - autoconf
          - automake
          - autotools-dev
          - bc
          - bison
          - build-essential
          - curl
          - dejagnu
          - expect
          - flex
          - gawk
          - gperf
          - libgmp-dev
          - libmpc-dev
          - libmpfr-dev
          - libtool
          - patchutils
          - texinfo
          - gcc-6
          - g++-6

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install zlib expat gawk gnu-sed; fi
  - export MAKEFLAGS="-j3"
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-6; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CC=gcc-6; fi
  - travis_wait 60 git submodule update --init --recursive

script:
  - ./configure --prefix=/tmp/build-default $CARGS
  # MacOS using clang by default, it will generate lots of warning message,
  # pipe stderr to stdout to prevent exceeded the maximum log length.
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_wait 90 scripts/wrapper/make_stderr_tail check;fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis_wait 90 scripts/wrapper/make_tail check;fi
  # MacOS don't support linux user mode for qemu, so there is only build
  # testing.
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis_wait 180 scripts/wrapper/make_tail check;fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make report check;fi

install: true
git:
  submodules: false
